# Generated by gallery/generate.py; do not edit.
function ars_technica_gallery:clear
# source-motor-north: source motor static shaft facing north
setblock 174 100 174 ars_technica:source_motor[facing=north]
# source-motor-south: source motor static shaft facing south
setblock 175 100 174 ars_technica:source_motor[facing=south]
# source-motor-west: source motor static shaft facing west
setblock 176 100 174 ars_technica:source_motor[facing=west]
# source-motor-east: source motor static shaft facing east
setblock 177 100 174 ars_technica:source_motor[facing=east]
# source-motor-up: source motor static shaft facing up
setblock 178 100 174 ars_technica:source_motor[facing=up]
# source-motor-down: source motor static shaft facing down
setblock 179 100 174 ars_technica:source_motor[facing=down]
# precise-relay-dry: precise relay static base pose
setblock 180 100 174 ars_technica:precise_relay[waterlogged=false]
# transmutation-turret-north: transmutation turret idle facing north
setblock 174 100 176 ars_technica:transmutation_turret[facing=north,triggered=false,waterlogged=false]
# transmutation-turret-south: transmutation turret idle facing south
setblock 175 100 176 ars_technica:transmutation_turret[facing=south,triggered=false,waterlogged=false]
# transmutation-turret-west: transmutation turret idle facing west
setblock 176 100 176 ars_technica:transmutation_turret[facing=west,triggered=false,waterlogged=false]
# transmutation-turret-east: transmutation turret idle facing east
setblock 177 100 176 ars_technica:transmutation_turret[facing=east,triggered=false,waterlogged=false]
# transmutation-turret-up: transmutation turret idle facing up
setblock 178 100 176 ars_technica:transmutation_turret[facing=up,triggered=false,waterlogged=false]
# transmutation-turret-down: transmutation turret idle facing down
setblock 179 100 176 ars_technica:transmutation_turret[facing=down,triggered=false,waterlogged=false]
# stock-control: stone stock rendering control
setblock 180 100 176 minecraft:stone
function ars_technica_gallery:verify
