# Generated by gallery/generate.py; do not edit.
execute unless block 174 100 174 ars_technica:source_motor[facing=north] run tellraw @a {"text":"gallery mismatch: source-motor-north","color":"red"}
execute unless block 175 100 174 ars_technica:source_motor[facing=south] run tellraw @a {"text":"gallery mismatch: source-motor-south","color":"red"}
execute unless block 176 100 174 ars_technica:source_motor[facing=west] run tellraw @a {"text":"gallery mismatch: source-motor-west","color":"red"}
execute unless block 177 100 174 ars_technica:source_motor[facing=east] run tellraw @a {"text":"gallery mismatch: source-motor-east","color":"red"}
execute unless block 178 100 174 ars_technica:source_motor[facing=up] run tellraw @a {"text":"gallery mismatch: source-motor-up","color":"red"}
execute unless block 179 100 174 ars_technica:source_motor[facing=down] run tellraw @a {"text":"gallery mismatch: source-motor-down","color":"red"}
execute unless block 180 100 174 ars_technica:precise_relay[waterlogged=false] run tellraw @a {"text":"gallery mismatch: precise-relay-dry","color":"red"}
execute unless block 174 100 176 ars_technica:transmutation_turret[facing=north,triggered=false,waterlogged=false] run tellraw @a {"text":"gallery mismatch: transmutation-turret-north","color":"red"}
execute unless block 175 100 176 ars_technica:transmutation_turret[facing=south,triggered=false,waterlogged=false] run tellraw @a {"text":"gallery mismatch: transmutation-turret-south","color":"red"}
execute unless block 176 100 176 ars_technica:transmutation_turret[facing=west,triggered=false,waterlogged=false] run tellraw @a {"text":"gallery mismatch: transmutation-turret-west","color":"red"}
execute unless block 177 100 176 ars_technica:transmutation_turret[facing=east,triggered=false,waterlogged=false] run tellraw @a {"text":"gallery mismatch: transmutation-turret-east","color":"red"}
execute unless block 178 100 176 ars_technica:transmutation_turret[facing=up,triggered=false,waterlogged=false] run tellraw @a {"text":"gallery mismatch: transmutation-turret-up","color":"red"}
execute unless block 179 100 176 ars_technica:transmutation_turret[facing=down,triggered=false,waterlogged=false] run tellraw @a {"text":"gallery mismatch: transmutation-turret-down","color":"red"}
execute unless block 180 100 176 minecraft:stone run tellraw @a {"text":"gallery mismatch: stock-control","color":"red"}
tellraw @a {"text":"Ars Technica gallery checked: 14 cases, 32 legal states routed","color":"green"}
